services:
  db1:
    container_name: db1
    image: db1-postgres:15
    build:
      context: ./db1
    restart: unless-stopped
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db1
      REPL_USER: replicator
      REPL_PASSWORD: replicator_pass
    command:
      - postgres
      - -c
      - config_file=/etc/postgresql/postgresql.conf
      - -c
      - hba_file=/etc/postgresql/pg_hba.conf
    #      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ./db1/data:/var/lib/postgresql
      - ./db1/conf/postgresql.conf:/var/lib/postgresql/data/postgresql.conf
      - ./db1/conf/pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf
    networks:
      - pg_net

  db2:
    container_name: db2
    image: db2-postgres:15
    build:
      context: ./db2
    user: "postgres"
    restart: unless-stopped
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db1
      REPL_USER: replicator
      REPL_PASSWORD: replicator_pass
    command:
      - /usr/local/bin/standby.sh
    #      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ./db2/data:/var/lib/postgresql
      - ./db2/conf/postgresql.conf:/var/lib/postgresql/data/postgresql.conf
      - ./db2/conf/pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf
    networks:
      - pg_net

  pgpool:
    image: pgpool/pgpool:latest
    ports:
      - "5432:5432"
    volumes:
      - ./pgpool/pgpool.conf:/config/pgpool.conf:ro
    environment:
      PGPOOL_CONF_VOLUME: /config
    depends_on:
      - db1
      - db2
    networks:
      - pg_net

networks:
  pg_net:
    driver: bridge
