listen_addresses = '*'
port = 5432
socket_dir = '/var/run/postgresql'

backend_clustering_mode = 'raw'

backend_hostname0 = 'db1'
backend_port0 = 5432
backend_weight0 = 1
backend_flag0 = 'ALLOW_TO_FAILOVER'

sr_check_period = 0
health_check_period = 0

num_init_children = 32
max_pool = 4
reserved_connections = 2

log_connections = on
log_hostname = on
log_per_node_statement = on